const imageList = [
    new TileImage(1, "images/background/background1.svg"),
    new TileImage(2, "images/background/background2.svg"),
    new TileImage(3, "images/background/background3.svg"),
    new TileImage(4, "images/background/backgroundMain1.svg"),
    new TileImage(5, "images/background/backgroundMain2.svg"),
    new TileImage(6, "images/background/backgroundMain3.svg"),
    new TileImage(7, "images/water/ocean1.svg"),
    new TileImage(8, "images/water/ocean2.svg"),
    new TileImage(9, "images/water/ocean3.svg"),
    new TileImage(10, "images/water/shallow1.svg"),
    new TileImage(11, "images/water/shallow2.svg"),
    new TileImage(12, "images/water/shallow3.svg"),
    new TileImage(13, "images/grass/grass1.svg"),
    new TileImage(14, "images/grass/grass2.svg"),
    new TileImage(15, "images/grass/grass3.svg"),
    new TileImage(16, "images/sand/sand1.svg"),
    new TileImage(17, "images/sand/sand2.svg"),
    new TileImage(18, "images/resources/lava/lavaCrack1.svg"),
    new TileImage(19, "images/resources/lava/lavaCrack2.svg"),
    new TileImage(20, "images/resources/lava/lavaCrack3.svg"),
];