const jamList = [
    new Jam("Monsters Inc", "incDoot.mp3", 0.1, "audio/mpeg", "Other"),
    new Jam("Chemistry Webquest", "chem.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Rattlesnake", "snok.mp3", 1, "audio/mpeg", "Words"),
    new Jam("BIG", "big.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Fire", "fire.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Home", "home.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Jimmy", "jimmy.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Ow", "ow.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("School", "school.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Stuck", "stuck.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Toenails", "toenails.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Aww Yeah", "yeah.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Harry Potter", "harryPotter.mp3", 1, "audio/mpeg", "Other"),
    new Jam("Roblox Oof", "roblox.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Bomb Alert", "bombAlert.wav", 0.2, "audio/wav", "Beeps"),
    new Jam("Breathing", "breathing.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Click 1", "click.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Click 2", "clt.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Cough", "cough.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Dink", "dnk.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Eh?", "eh.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Mmm", "mmm.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Pfth", "pfth.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Ptt", "ptt.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Slurp", "slurp.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Thump", "thump.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Wet Stomp", "stompWet.wav", 1, "audio/wav", "Bodily Sounds"),
    new Jam("Dododoo", "dododoo.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Duh", "duh.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Heehee", "heehee.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Sniff", "sniff.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Thart", "thart.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Uhoh", "uhoh.mp3", 1, "audio/mpeg", "Words"),
    new Jam("Zzz", "zzz.mp3", 1, "audio/mpeg", "Bodily Sounds"),
    new Jam("Laugh", "laugh.mp3", 1, "audio/mpeg", "Words")
];