const jamList = [
    new Jam("Monsters Inc", "incDoot.mp3", 0.1, "audio/mpeg"),
    new Jam("Chemistry Webquest", "chem.mp3", 1, "audio/mpeg"),
    new Jam("Rattlesnake", "snok.mp3", 1, "audio/mpeg"),
    new Jam("BIG", "big.mp3", 1, "audio/mpeg"),
    new Jam("Fire", "fire.mp3", 1, "audio/mpeg"),
    new Jam("Home", "home.mp3", 1, "audio/mpeg"),
    new Jam("Jimmy", "jimmy.mp3", 1, "audio/mpeg"),
    new Jam("Ow", "ow.mp3", 1, "audio/mpeg"),
    new Jam("School", "school.mp3", 1, "audio/mpeg"),
    new Jam("Stuck", "stuck.mp3", 1, "audio/mpeg"),
    new Jam("Toenails", "toenails.mp3", 1, "audio/mpeg"),
    new Jam("Aww Yeah", "yeah.mp3", 1, "audio/mpeg"),
    new Jam("Harry Potter", "harryPotter.mp3", 1, "audio/mpeg"),
    new Jam("Roblox Oof", "roblox.mp3", 1, "audio/mpeg"),
    new Jam("Bomb Alert", "bombAlert.wav", 0.2, "audio/wav"),
    new Jam("Breathing", "breathing.mp3", 1, "audio/mpeg"),
    new Jam("Click", "click.mp3", 1, "audio/mpeg"),
    new Jam("Clt", "clt.mp3", 1, "audio/mpeg"),
    new Jam("Cough", "cough.mp3", 1, "audio/mpeg"),
    new Jam("Dnk", "dnk.mp3", 1, "audio/mpeg"),
    new Jam("Eh?", "eh.mp3", 1, "audio/mpeg"),
    new Jam("Mmm", "mmm.mp3", 1, "audio/mpeg"),
    new Jam("Pfth", "pfth.mp3", 1, "audio/mpeg"),
    new Jam("Ptt", "ptt.mp3", 1, "audio/mpeg"),
    new Jam("Slurp", "slurp.mp3", 1, "audio/mpeg"),
    new Jam("Thump", "thump.mp3", 1, "audio/mpeg")
];