var answers = [
    new Solution([
        ['n','o','d','s'],
        ['o','v','a','l'],
        ['v','e','t','o'],
        ['a','n','e','w']],
        ['Head signal yes or no','Ellipse in dumby speak','President say no no','To be reborn ____',
        'Super ____','Where you bake or make a cake','Simon will get one in 50,000 years','No zoom zoom']),
    new Solution([
        ['b','a','t','s'],
        ['e','u','r','o'],
        ['s','t','a','b'],
        ['t','o','y','s']],
        ['Bards Against the Throne (Owl House)','EU money','Poke with a knife','____ R US',
        'Bert is the ____','Not manual','Food goes on it','Big cry cry']),
    new Solution([
        ['l','u','s','h'],
        ['a','l','o','e'],
        ['g','n','a','r'],
        ['s','a','p','s']],
        ['Full of life','Plant for burn $14.99','A snarl growl','Tree blood (plural)',
        'My excuse for losing pew pew','Bone of forearm','Cleaning rectangle','Not his but ____']),
    new Solution([
        ['m','e','s','a'],
        ['e','v','e','s'],
        ['g','e','e','k'],
        ['a','n','d','s']],
        ['Flat topped hill','Day before (plural)','Nerd culture subset','&&, !(!x || !y)',
        '10^6 (M)',"I literally can't ____",'Baby plant','Pose a question']),
    new Solution([
        ['k','i','t','s'],
        ['i','d','o','l'],
        ['d','e','l','i'],
        ['s','a','l','t']],
        ['Lego ____','Hero','Where you buy the sliced ham','Pure flavor (Bert logic)',
        'Baby goats','When you do a thinky think of a thing and the little light bulb comes on','Bells do it','Little cut']),
    new Solution([
        ['p','u','g','s'],
        ['o','m','i','t'],
        ['e','m','m','y'],
        ['t','a','p','e']],
        ['The disfigured dogs','Whoops. Forgot to give a hint here','Prize for acting','Better than glue',
        'Rhyme writer','Some muslim thing (according to dictionary)','Twisted silk','Pig ____']),
    new Solution([
        ['j','a','v','a'],
        ['i','c','e','d'],
        ['b','r','a','d'],
        ['e','e','l','s']],
        ['The coding language that gives you energy to start your day right.','If you make your drink like this, Bert will murder you and sell your soul.','You was born in a pitt.','The wet slimy slugs that do big ouch.',
         'When you mock somebody\'s intestines.','When you need more farmland, sell your soul for another _.','When you murder sheep and then eat them.','math']),
    new Solution([
        ['d','o','r','k'],
        ['o','p','e','n'],
        ['l','a','m','e'],
        ['e','l','s','e']],
        ['Me (garm) in a nutshell.','When you take a door, you throw it across the room, chop it into little tiny pieces, murder your secretary, jump out the window into the mattress you put there two and a half months ago just in case, the door casing is now _.','this hint compared to the last one','One of the only two coding condtionals you need',
         'Those weirdos who make fruit cups that are really high on sugar.','Pearl + Amethyst.','When you do the dreaming but plural but like that\'s not actually what this word means but I don\'t care.','Caput, umeri, GENEI, et digiti']),
    new Solution([
        ['m','e','w','s'],
        ['a','c','h','e'],
        ['p','r','o','w'],
        ['s','u','m','s']],
        ['That thing that the cat does when it really wants food and it\'s like hey you stupid idiotic human feed me or die.','You know, it\'s something that your back does after the cat attacks it because you didn\'t feed it.','That one part of a boat.','∑',
         'The thing that was used to navigate your car back in the day when your mother was still young.','idk man it\'s some color just do the other clues and let this one fill itself in','Another form of who.','When you accidently rip your shirt, you have to ___ it back together, except throw on an s at the end because like this isn\'t actually a good scenario to use this word.']),
    new Solution([
        ['p','e','a','s'],
        ['i','d','l','e'],
        ['c','i','t','e'],
        ['a','t','o','m']],
        ['Little green balls.','The best tipe of video game.','The worst part of writing a research paper.','Little small things in the air.',
         '_CHU (but not quite).','The actual worst part of writing a research paper.','A type of saxophone.','So it may']),
    new Solution([
        ['l','a','s','t'],
        ['e','x','p','o'],
        ['a','l','a','s'],
        ['k','e','y','s']],
        ['F I N A L.','Where you go to show off how much of a nerd you is.','But ____, the donkeys could just not be stopped.','The things that go jingle jangle but not those things.',
         'That\'s a lot of damage.','The thing in the middle of a motorcycl tire. Rip bert\'s motorcycle: 11:36 pm.','When you tell your dog it no longer has a gender.','To throw something away, for example, a chance to ride a motorcycle.']),
    new Solution([
        ['','','',''],
        ['','','',''],
        ['','','',''],
        ['','','','']],
        ['','','','','','','','']),
    new Solution([
        ['','','',''],
        ['','','',''],
        ['','','',''],
        ['','','','']],
        ['','','','','','','','']),
    new Solution([
        ['','','',''],
        ['','','',''],
        ['','','',''],
        ['','','','']],
        ['','','','','','','','']),
    new Solution([
        ['','','',''],
        ['','','',''],
        ['','','',''],
        ['','','','']],
        ['','','','','','','',''])
];
